# Generated by Django 4.2.5 on 2023-09-16 12:06

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='book name')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
                ('number_of_pages', models.PositiveBigIntegerField(verbose_name='number of pages')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='Books publish time')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'Books',
            },
        ),
    ]
